name: Check Linting

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Create virtual environment
              run: python3 -m venv venv && source venv/bin/activate
            - name: Install required packages
              run: pip3 install -r requirements.txt
            - name: Check Formatting
              run: ./scripts/format.sh &&  git diff --exit-code
            - name: Check MyPy Type Hinting
              run: python3 -m mypy tj_adapt_vqe/
            - name: Check PyFlakes
              run: python3 -m pyflakes tj_adapt_vqe/