name: Check Typing

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    typing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Create virtual environment
              run: python3 -m venv venv && source venv/bin/activate
            - name: Install required packages
              run: pip3 install -r requirements.txt
            - name: Check Typing
              run: python3 -m mypy tj_adapt_vqe/
            - name: Check for Errors
              run: git diff --exit-code